version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  blazor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blazor-app
    depends_on:
      - mysql
    ports:
      - "5091:80"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Port=3306;Database=app_db;User=user;Password=userpassword;

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
